### PR TITLE
DevOps Tool Integration

### PR DESCRIPTION
**Pull request by YourEpicness**
Hello Team!

I have incorporated automated testing, linting, and CI with Github Actions. This was honestly just to play around and not necessary for the project. But, as we continue working on the project I believe that it will come in handy with making sure our code is clean and works for everyone. There will be a green check or red X that will be generated after every push/pull request. And hopefully, linting is automatically applied on every submission. I'll handle all the automation stuff moving forward so you don't have to worry about it too much. Please try and fork/git pull to see if you get a green check.

Thanks!

### CODE REVIEW

**Comment by YourEpicness** [comment]
[DevOps Integration Pull Request](https://trello.com/c/oMFfRSOz/8-devops-integration-pull-request)

**Comment by tforthomas73** [comment]
Looks good to me!

**Review by tforthomas73 — APPROVED** [review]
Looks good

**Review by yeiltza — APPROVED** [review]
I have no proof this works but no doubts in your intelligence and execution please don't break our app...
will go over it with you in person though

**Pull request merged**
